language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
- linux
- osx

script:
  - cargo build -v
  - cargo test -v
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo test --features "nightly"; fi
  - cargo doc -v
