[package]
edition = "2024"
name = "codex-otel"
version = { workspace = true }

[lib]
name = "codex_otel"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[features]
# Compile-time gate for OTLP support; enabled by default. Downstream crates can
# disable `otel` and enable `otel-shim` for environments without OTLP exporters.
default = ["otel"]
otel = [
    "opentelemetry",
    "opentelemetry_sdk",
    "opentelemetry-otlp",
    "tonic",
]
otel-shim = []

[dependencies]
codex-protocol = { path = "../protocol" }
chrono = { workspace = true }
tracing = { workspace = true }
opentelemetry = { workspace = true, features = ["logs"], optional = true }
opentelemetry_sdk = { workspace = true, features = ["logs", "rt-tokio"], optional = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic", "http-proto", "http-json", "reqwest", "reqwest-rustls"], optional = true }
opentelemetry-semantic-conventions = { workspace = true }
tonic = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
reqwest = { workspace = true }
eventsource-stream = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
