# Codespell configuration is within .codespellrc
---
name: Codespell (disabled)

# Disabled for this fork; run manually if needed.
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  codespell:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Codespell disabled. Use workflow_dispatch to run manually."
