name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/test.yml'
      - 'examples/**'
      - '**/*.test.ts'
      - 'test/**'
      - '*.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  determine-version:
    name: Determine Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Determine next version
        id: version
        working-directory: codex-cli
        shell: bash
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version in package.json: $CURRENT_VERSION"
          PUBLISHED_VERSION=$(npm view @just-every/code version 2>/dev/null || echo "0.0.0")
          echo "Latest published version: $PUBLISHED_VERSION"

          if [ "$CURRENT_VERSION" = "$PUBLISHED_VERSION" ] || [ "$CURRENT_VERSION" \< "$PUBLISHED_VERSION" ]; then
            IFS='.' read -ra V <<< "$PUBLISHED_VERSION"
            NEW_VERSION="${V[0]}.${V[1]}.$((${V[2]} + 1))"
          else
            NEW_VERSION=$CURRENT_VERSION
          fi

          echo "version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"

  build-binaries:
    name: Build ${{ matrix.target }}
    needs: determine-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            artifact: code-x86_64-unknown-linux-musl
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            artifact: code-x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
            artifact: code-aarch64-unknown-linux-musl
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            artifact: code-aarch64-unknown-linux-gnu
          # macOS builds
          - os: macos-14
            target: x86_64-apple-darwin
            artifact: code-x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
            artifact: code-aarch64-apple-darwin
          # Windows build
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: code-x86_64-pc-windows-msvc.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Rust (needed before using cargo)
      - name: Install Rust (minimal)
        shell: bash
        run: |
          rustup set profile minimal
          rustup toolchain install 1.89.0 --profile minimal --target ${{ matrix.target }}
          rustup default 1.89.0

      # 🔧 Update workspace package version in Cargo.toml (portable)
      # Prefer [workspace.package], fallback to [package] if present
      - name: Set crate version in Cargo.toml (portable)
        shell: bash
        working-directory: codex-rs
        run: |
          set -euo pipefail
          VERSION="${{ needs.determine-version.outputs.version }}"
          echo "Embedding version ${VERSION} into codex-rs/Cargo.toml"
          awk -v ver="$VERSION" '
            BEGIN{in_ws_pkg=0; in_pkg=0; done=0}
            /^\[workspace\.package\]/{in_ws_pkg=1; in_pkg=0}
            /^\[package\]/{in_pkg=1; in_ws_pkg=0}
            /^\[/{ if ($0 !~ /^\[(workspace\.package|package)\]/) { in_ws_pkg=0; in_pkg=0 } }
            {
              if ((in_ws_pkg || in_pkg) && !done && $0 ~ /^version[[:space:]]*=/) {
                print "version = \"" ver "\""; done=1; next
              }
              print
            }
          ' Cargo.toml > Cargo.toml.tmp && mv Cargo.toml.tmp Cargo.toml
          echo "New version line:" && awk '/^\[(workspace\.package|package)\]/{in=1; next} /^\[/{in=0} in && /^version[[:space:]]*=/{print; exit}' Cargo.toml || true

      # 🔒 Keep lockfile consistent for --frozen without changing deps
      - name: Regenerate lockfile for --frozen
        shell: bash
        working-directory: codex-rs
        run: cargo generate-lockfile

      # Cache target/ + registries (to skip linking when unchanged)
      - name: Setup Rust Cache (target + registries)
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v4-rust
          shared-key: codex-${{ matrix.target }}-rust-1.89-target
          workspaces: |
            codex-rs -> target
          cache-targets: true
          cache-workspace-crates: true
          cache-on-failure: true

      # Stable sccache namespace per toolchain+target
      - name: Configure sccache cache keys
        shell: bash
        run: echo "SCCACHE_GHA_VERSION=${{ matrix.target }}-rust-1.89-v4" >> "$GITHUB_ENV"

      - name: Setup sccache (GHA backend)
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: v0.10.0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Enable sccache for Rust compiles
      - name: Enable sccache
        shell: bash
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
          echo "SCCACHE_IDLE_TIMEOUT=1800" >> "$GITHUB_ENV"
          echo "SCCACHE_CACHE_SIZE=10G" >> "$GITHUB_ENV"

      # ---------------------------
      # Platform-specific tuning
      # ---------------------------

      # Linux GNU: mold linker + C/C++ through sccache (clang preferred)
      - name: Linux (gnu) tuning
        if: contains(matrix.os, 'ubuntu') && contains(matrix.target, 'gnu')
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y mold || true
          if command -v clang >/dev/null 2>&1; then
            echo 'CC=sccache clang'    >> "$GITHUB_ENV"
            echo 'CXX=sccache clang++' >> "$GITHUB_ENV"
          else
            echo 'CC=sccache gcc'      >> "$GITHUB_ENV"
            echo 'CXX=sccache g++'     >> "$GITHUB_ENV"
          fi
          echo 'RUSTFLAGS=-Awarnings -C link-arg=-fuse-ld=mold -C debuginfo=0 -C strip=symbols -C panic=abort' >> "$GITHUB_ENV"

      # Linux MUSL: build & link with musl-gcc to avoid glibc symbol leakage
      - name: Linux (musl) tuning
        if: contains(matrix.os, 'ubuntu') && contains(matrix.target, 'musl')
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config
          # Use musl headers + libs for all C compiles (no sccache wrapper here for reliability)
          echo 'CC=musl-gcc' >> "$GITHUB_ENV"
          # Ensure rustc links with musl-gcc (avoids __isoc23_strtol glibc symbol)
          case "${{ matrix.target }}" in
            x86_64-unknown-linux-musl) echo 'CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc' >> "$GITHUB_ENV" ;;
            aarch64-unknown-linux-musl) echo 'CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=musl-gcc' >> "$GITHUB_ENV" ;;
          esac
          echo 'PKG_CONFIG_ALLOW_CROSS=1' >> "$GITHUB_ENV"
          echo 'OPENSSL_STATIC=1'         >> "$GITHUB_ENV"
          echo 'RUSTFLAGS=-Awarnings -C debuginfo=0 -C strip=symbols -C panic=abort' >> "$GITHUB_ENV"

      # macOS: Homebrew LLVM + LLD; C/C++ through sccache; link via ld64.lld
      - name: macOS toolchain & linker (brew clang + lld via sccache)
        if: startsWith(matrix.os, 'macos-')
        shell: bash
        run: |
          set -euo pipefail
          brew install llvm lld || true
          LLVM_PREFIX="$(brew --prefix llvm || true)"
          LLD_PREFIX="$(brew --prefix lld || true)"
          [[ -n "${LLVM_PREFIX}" && -n "${LLD_PREFIX}" ]] || { echo "brew llvm/lld not found"; exit 1; }
          echo "${LLVM_PREFIX}/bin" >> "$GITHUB_PATH"
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> "$GITHUB_ENV"
          echo "CC=sccache clang"    >> "$GITHUB_ENV"
          echo "CXX=sccache clang++" >> "$GITHUB_ENV"
          echo "RUSTFLAGS=-Awarnings -Clinker=clang -C link-arg=-fuse-ld=${LLD_PREFIX}/bin/ld64.lld -C debuginfo=0 -C strip=symbols -C panic=abort" >> "$GITHUB_ENV"

      # Windows: lld-link + prebuilt OpenSSL via vcpkg (cached)
      - name: Enable lld-link (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          "RUSTFLAGS=-Clinker=lld-link -C codegen-units=16 -C debuginfo=0 -C strip=symbols -C panic=abort -C link-arg=/OPT:REF -C link-arg=/OPT:ICF -C link-arg=/DEBUG:NONE" >> $env:GITHUB_ENV

      - name: Cache vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v4
        with:
          path: |
            ~\vcpkg\installed
            ~\vcpkg\packages
          key: vcpkg-openssl-${{ runner.os }}-x64-windows

      - name: Install OpenSSL via vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          if (!(Test-Path "$env:USERPROFILE\vcpkg")) {
            git clone https://github.com/microsoft/vcpkg $env:USERPROFILE\vcpkg
            & $env:USERPROFILE\vcpkg\bootstrap-vcpkg.bat
          }
          & $env:USERPROFILE\vcpkg\vcpkg.exe install openssl:x64-windows
          "VCPKG_ROOT=$env:USERPROFILE\vcpkg" >> $env:GITHUB_ENV
          "OPENSSL_NO_VENDOR=1"               >> $env:GITHUB_ENV

      # Prefetch deps so --frozen works offline (needed for git deps like ratatui)
      - name: Prefetch dependencies (git + registry)
        working-directory: codex-rs
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: "true"
        run: cargo fetch --locked

      # Pass chosen npm version into the Rust build (optional build.rs exposes it)
      - name: Export CODE_VERSION for Rust build
        shell: bash
        run: echo "CODE_VERSION=${{ needs.determine-version.outputs.version }}" >> "$GITHUB_ENV"

      - name: Build binaries (with timings)
        shell: bash
        env:
          CARGO_INCREMENTAL: "0"
          RUST_BACKTRACE: "1"
        run: |
          cd codex-rs
          cargo build --release --frozen --locked --timings --target ${{ matrix.target }} --bin code --bin code-tui --bin code-exec

      - name: sccache stats (human + json)
        shell: bash
        run: |
          sccache --show-stats || true
          sccache --show-stats --stats-format=json || true

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp codex-rs/target/${{ matrix.target }}/release/code.exe artifacts/${{ matrix.artifact }}
            cp codex-rs/target/${{ matrix.target }}/release/code-tui.exe artifacts/code-tui-${{ matrix.target }}.exe
            cp codex-rs/target/${{ matrix.target }}/release/code-exec.exe artifacts/code-exec-${{ matrix.target }}.exe
          else
            cp codex-rs/target/${{ matrix.target }}/release/code artifacts/${{ matrix.artifact }}
            cp codex-rs/target/${{ matrix.target }}/release/code-tui artifacts/code-tui-${{ matrix.target }}
            cp codex-rs/target/${{ matrix.target }}/release/code-exec artifacts/code-exec-${{ matrix.target }}
          fi

      - name: Upload binaries (no compression)
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.target }}
          path: artifacts/
          compression-level: 0

      - name: Upload cargo timings
        uses: actions/upload-artifact@v4
        with:
          name: cargo-timings-${{ matrix.target }}
          path: codex-rs/target/cargo-timings/*.html
          if-no-files-found: ignore
          compression-level: 0

  release:
    name: Publish to npm
    needs: [determine-version, build-binaries]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Prepare release assets
        shell: bash
        run: |
          mkdir -p release-assets
          for dir in artifacts/binaries-*; do
            cp "$dir"/* release-assets/
          done
          chmod +x release-assets/* || true
          ls -la release-assets/

      - name: Sync README for npm
        shell: bash
        run: cp README.md codex-cli/README.md

      - name: Update package.json version
        id: version
        working-directory: codex-cli
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          NEW_VERSION="${{ needs.determine-version.outputs.version }}"
          npm version "$NEW_VERSION" --no-git-tag-version --allow-same-version
          echo "version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"
          git add package.json
          if git diff --staged --quiet; then
            echo "skip_push=true" >> "$GITHUB_OUTPUT"
          else
            git commit -m "chore(release): ${NEW_VERSION} [skip ci]"
            echo "skip_push=false" >> "$GITHUB_OUTPUT"
          fi
          if ! git rev-parse "v${NEW_VERSION}" >/dev/null 2>&1; then
            git tag "v${NEW_VERSION}"
          fi
          echo "tag=v${NEW_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Check if we should publish
        id: should_publish
        shell: bash
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "publish=false" >> "$GITHUB_OUTPUT"
          else
            echo "publish=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Publish to npm
        if: steps.should_publish.outputs.publish == 'true'
        working-directory: codex-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - name: Push tag
        shell: bash
        run: git push origin "v${{ steps.version.outputs.version }}" || true

      - name: Push changes
        if: steps.version.outputs.skip_push != 'true'
        shell: bash
        run: |
          git push origin main
          git push origin --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            ## @just-every/code v${{ steps.version.outputs.version }}

            Fork of OpenAI Codex with additional features:
            - Enhanced image handling (drag-and-drop, paste, file path detection)
            - /reasoning slash command for dynamic reasoning effort

            ### Installation
            ```bash
            npm install -g @just-every/code
            ```

            ### Usage
            ```bash
            code
            ```
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
