name: Release

on:
  push:
    branches: [ code-release ]
    paths-ignore:
      - '.github/workflows/test.yml'
      - 'examples/**'
      - '**/*.test.ts'
      - 'test/**'
      - '*.md'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-binaries:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact: code-x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact: code-aarch64-unknown-linux-musl
          - os: macos-13  # Use Intel Mac for x86_64 builds
            target: x86_64-apple-darwin
            artifact: code-x86_64-apple-darwin
          - os: macos-latest  # Use ARM Mac for aarch64 builds
            target: aarch64-apple-darwin
            artifact: code-aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: code-x86_64-pc-windows-msvc.exe
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Add Rust target
      run: rustup target add ${{ matrix.target }}
        
    - name: Install musl tools (Linux x86_64)
      if: matrix.target == 'x86_64-unknown-linux-musl'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
        
    - name: Install musl tools (Linux aarch64)
      if: matrix.target == 'aarch64-unknown-linux-musl'
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu
        # Set up cross compilation
        echo "CC_aarch64_unknown_linux_musl=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        echo "AR_aarch64_unknown_linux_musl=aarch64-linux-gnu-ar" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        
    - name: Build binaries
      run: |
        cd codex-rs
        cargo build --release --target ${{ matrix.target }} --bin code --bin code-tui --bin code-exec
        
    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cp codex-rs/target/${{ matrix.target }}/release/code.exe artifacts/${{ matrix.artifact }}
          cp codex-rs/target/${{ matrix.target }}/release/code-tui.exe artifacts/code-tui-${{ matrix.target }}.exe
          cp codex-rs/target/${{ matrix.target }}/release/code-exec.exe artifacts/code-exec-${{ matrix.target }}.exe
        else
          cp codex-rs/target/${{ matrix.target }}/release/code artifacts/${{ matrix.artifact }}
          cp codex-rs/target/${{ matrix.target }}/release/code-tui artifacts/code-tui-${{ matrix.target }}
          cp codex-rs/target/${{ matrix.target }}/release/code-exec artifacts/code-exec-${{ matrix.target }}
        fi
      shell: bash
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.target }}
        path: artifacts/

  release:
    name: Publish to npm
    needs: build-binaries
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Skip if commit message contains [skip ci]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        
    - name: Prepare binaries for npm
      run: |
        # Create bin directory in codex-cli
        mkdir -p codex-cli/bin
        
        # Copy all binaries to the bin directory
        for dir in artifacts/binaries-*; do
          cp $dir/* codex-cli/bin/
        done
        
        # Make binaries executable
        chmod +x codex-cli/bin/*
        
        # List binaries for verification
        ls -la codex-cli/bin/
        
    - name: Bump version
      id: version
      working-directory: codex-cli
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Get current version
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Bump version
        npm version patch --no-git-tag-version
        NEW_VERSION=$(node -p "require('./package.json').version")
        echo "New version: $NEW_VERSION"
        echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        
        # Commit changes
        git add package.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
          echo "skip_push=true" >> $GITHUB_OUTPUT
        else
          git commit -m "chore(release): ${NEW_VERSION} [skip ci]"
          git tag "v${NEW_VERSION}"
          echo "skip_push=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Check if we should publish
      id: should_publish
      run: |
        if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
          echo "NPM_TOKEN not set, skipping publish"
          echo "publish=false" >> $GITHUB_OUTPUT
        else
          echo "NPM_TOKEN is set, will publish"
          echo "publish=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Publish to npm
      working-directory: codex-cli
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      if: steps.should_publish.outputs.publish == 'true'
        
    - name: Push changes
      run: |
        git push origin code-release
        git push origin --tags
      if: steps.version.outputs.skip_push != 'true'
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: steps.version.outputs.skip_push != 'true'
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body: |
          ## @just-every/code v${{ steps.version.outputs.version }}
          
          Fork of OpenAI Codex with additional features:
          - Enhanced image handling (drag-and-drop, paste, file path detection)
          - /reasoning slash command for dynamic reasoning effort
          
          ### Installation
          ```bash
          npm install -g @just-every/code
          ```
          
          ### Usage
          ```bash
          code
          ```
        files: |
          artifacts/binaries-*/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}